/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home_in_patagonia.views;

import home_in_patagonia.controllers.MovieController;
import home_in_patagonia.models.Movie;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ProBook
 */
public class VistaListarMovies extends javax.swing.JFrame {

    private MovieController movieController;
    private JTable jTable;
    private JScrollPane jScrollPane;

    /**
     * Creates new form VistaListarMovies
     */
    public VistaListarMovies(MovieController movieController) {
        initComponents();
        this.movieController = movieController;

        List<Movie> movies = movieController.getMovieFromDB();

        //Determino la manera en la que se mostraran los datos en la tabla
        String[] columnNames = {"Id", "Titulo", "Director", "Año", "Duracion", "Genero"};
        //Calculo la cantidad de datos que vienen, para que la tabla no se sobredimencione
        Object[][] data = new Object[movies.size()][columnNames.length];

        for (int i = 0; i < movies.size(); i++) {
            Movie movie = movies.get(i);
            data[i][0]= movie.getIdMovie();
            data[i][1]= movie.getTitulo();
            data[i][2]= movie.getDirector();
            data[i][3]= movie.getAño();
            data[i][4]= movie.getDuracion();
            data[i][5]= movie.getGenero();
        }
        DefaultTableModel model  = new DefaultTableModel(data, columnNames);
        jTable1.setModel(model);
        ((DefaultTableModel) jTable1.getModel()).fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
